import {Roboto, Press_Start_2P, Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";


const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: ["400", "500", "700"]
})
const pressStart = Press_Start_2P({
    weight: "400",
    variable: "--font-press-start",
    subsets: ["latin"],
});
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`
           ${roboto.variable} ${geistSans.variable} ${geistMono.variable} ${pressStart.variable} antialiased`}

        >
        <Navbar  />
        <main>
            {children}</main>
        <footer><Footer/></footer>
        </body>
        </html>
    );
}
